### ISSUE TITLE
[BUG] [Linux AppImage 0.4.2] Dashes and underscores stop creating melismas

### ISSUE THREAD

**Issue by PeTH2** [danielgarthur/neanes#236] opened 2023-08-22 16:46 UTC
- [x] Desktop

After editing a piece for a few minutes, dashes will no longer create melismas. If the notes are copied into a fresh file the same thing will apply.

1. Begin editing
2. after a little while dashes/underscores will no longer create melismas, regardless of keybd. layout.

Linux AppImage (Arch Linux, 6.1.45-1-lts)

![melisma bug](https://github.com/danielgarthur/neanes/assets/128826899/3684ae95-54ff-4724-b202-d4df03453eea)
out]

**Comment by danielgarthur** [comment] 2023-08-22 22:13
**Additional Information**

The trigger is typing `-` or `_` in a lyric box. After a lyric box has taken one of these characters, it becomes buggy. Melismas can no longer be set, and the text box cannot be navigated to with the arrow keys.

This can be reproduced by

1. Create a new score.
2. Add two isons.
3. Type `test-` as the lyric for the first ison. Then `ing` for the second ison.
4. Try to navigate to the first lyrics box by pressing the left arrow. It doesn't work.
5. Click the first lyrics and type `-` at the end of the lyrics. Instead of moving to the second ison, an extra `-` is entered.

**Resolution**

This appears to be another Vue 3 issue. For some reason, using the key helper to refresh the lyrics puts the lyrics box into an unusual state. 

As it turns out, using the key helper to refresh the lyrics box is not necessary since we can instead call a direct method on the `ContentEditable` component to set the text. Switching to this pattern seems to have fixed it.

**Comment by danielgarthur** [comment] 2023-08-22 23:43
Fixed in release `0.4.3`.

**Closed by danielgarthur** 2023-08-22 23:43 UTC
Labels: bug
