### ISSUE TITLE
[ENHANCEMENT] Show keyboard combination on mouse hovering

### ISSUE THREAD

**Issue by dimii27** [danielgarthur/neanes#465] opened 2023-12-12 11:31 UTC
When still learining to use this program there is some learing curve which is mostly due to the neume imput you have to get used to.

My suggestion is to be able to see the corresponding keyboard combination of each neume when hovering with the mouse for a moment so that you don't have to Alt+Tab to the website to the corresponding table for the keyboard shortcut.

Maybe not everyone would like this addition so it could have a checkbox to turn on/off.

**Comment by danielgarthur** [comment] 2023-12-12 14:52
This request is currently captured in #269 and is partially complete. Hovering over the neumes in the left pane shows the keyboard shortcut. The tooltips will be expanded to show shortcuts for certain buttons in the bottom toolbars, as well.  

I'm closing this ticket, since it is a duplicate of #269. Please check that ticket for progress updates on the feature.

**Closed by danielgarthur** 2023-12-12 14:52 UTC
Labels: duplicate, enhancement
